server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/cinestream_db
    username: postgres
    password: p1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: true

  graphql:
    graphiql:
      enabled: true

  data:
    redis:
      host: localhost
      port: 6379

  cache:
    type: redis

jwt:
  secret: cineStreamSuperSecretKeyMustBeAtLeast32CharactersLong123
  expiration-ms: 86400000